In [1]:
arr1 = np.arange(4, dtype = np.float_).reshape(2, 2)


NameError: name 'np' is not defined

In [2]:
import numpy as np 


In [3]:
arr1 = np.arange(4, dtype = np.float_).reshape(2, 2)


In [4]:
print(arr1)

[[0. 1.]
 [2. 3.]]


In [5]:
print('\nSecond array:') 
arr2 = np.array([12, 12]) 
print(arr2)


Second array:
[12 12]


In [6]:
print('\nAdding the two arrays:') 
print(np.add(arr1, arr2))


Adding the two arrays:
[[12. 13.]
 [14. 15.]]


In [7]:
print('\nSubtracting the two arrays:') 
print(np.subtract(arr1, arr2))


Subtracting the two arrays:
[[-12. -11.]
 [-10.  -9.]]


In [8]:
print('\nMultiplying the two arrays:')
print(np.multiply(arr1, arr2))


Multiplying the two arrays:
[[ 0. 12.]
 [24. 36.]]


In [9]:
print('\nDividing the two arrays:')
print(np.divide(arr1, arr2))


Dividing the two arrays:
[[0.         0.08333333]
 [0.16666667 0.25      ]]


In [10]:
import numpy as np 
arr = np.array([25, 1.33, 1, 1, 100]) 

In [11]:
print('Our array is:')
print(arr)

Our array is:
[ 25.     1.33   1.     1.   100.  ]


In [ ]:
arr.dtype

In [12]:
print('\nAfter applying reciprocal function:') 
print(np.reciprocal(arr))


After applying reciprocal function:
[0.04      0.7518797 1.        1.        0.01     ]


In [13]:
arr2 = np.array([25], dtype = int)
print('\nThe second array is:')
print(arr2)


The second array is:
[25]


In [14]:
print('\nAfter applying reciprocal function:') 
print(np.reciprocal(arr2))


After applying reciprocal function:
[0]


In [15]:
import numpy as np
arr = np.array([5, 10, 15]) 
 
print('First array is:') 
print(arr)

First array is:
[ 5 10 15]


In [16]:
print('\nApplying power function:') 
print(np.power(arr, 2))


Applying power function:
[ 25 100 225]


In [17]:
print('\nSecond array is:') 
arr1 = np.array([1, 2, 3]) 
print(arr1)


Second array is:
[1 2 3]


In [18]:
print('\nApplying power function again:') 
print(np.power(arr, arr1))


Applying power function again:
[   5  100 3375]


In [24]:
arr = np.array([5, 15, 20]) 
arr1 = np.array([2, 5, 9]) 

In [25]:
print('First array:') 
print(arr) 

First array:
[ 5 15 20]


In [26]:
print('\nSecond array:') 
print(arr1)


Second array:
[2 5 9]


In [27]:
print('\nApplying mod() function:') 
print(np.mod(arr, arr1))


Applying mod() function:
[1 0 2]


In [28]:
print('\nApplying remainder() function:') 
print(np.remainder(arr, arr1))


Applying remainder() function:
[1 0 2]


In [29]:
import numpy as np

In [30]:
print(np.char.split('geeks for geeks'))

['geeks', 'for', 'geeks']


In [31]:
print(np.char.split('geeks, for, geeks', sep = ','))

['geeks', ' for', ' geeks']
